### ISSUE TITLE
Currents - Stuck Sensor Test

### ISSUE THREAD

**Issue by lukecampbell** [asascience-open/QARTOD#56]
Verify that the existing stuck sensor test meets the criteria specified here:
![screen shot 2015-10-01 at 11 41 44 am](https://cloud.githubusercontent.com/assets/1155163/10225575/7c78aa9e-6831-11e5-8da6-a0deff594479.png)

If it doesn't then:
- [ ] QARTOD test implemented
- [ ] Unit test implemented

**Comment by ocefpaf** [comment]
@lukecampbell if my understanding is correct this test is the similar to  `flat_line_check` with the default values `low_reps=2` and `high_reps=5`, correct?

**Comment by lukecampbell** [comment]
Yeah that's my understanding as well

**Comment by ocefpaf** [comment]
After some reading I found that `Stuck Sensor Test` is "outdated."
In page `v` of [qartod_wave_data_manual.pdf](http://www.ioos.noaa.gov/qartod/wave_data/qartod_wave_data_manual.pdf):

```
Change Stuck Sensor Test (Test 16) to Flat Line Test
(pages 13, 14, 35, and Table of Contents)
```

(Read all 9 manuals and of course the information was in the last one!)

The full name of the test, in pages 13, 14, 32 (not 35), is **LT Time Series Flat Line (Test 16)**.

Questions:

  1. Should we add this one too?  Or should we just wrap **Flat Line (Test 8)** with modified inputs? (This version suggests the defaults of `low_reps=3, high_reps=5`.)

  2. If I get the `@add_qartod_ident` decorator correctly the number is the `QARTOD ID` and the text is the `test name`.  If so this test must be decorate with `@add_qartod_ident(16, 'Time Series Flat Line Test')`. Is that correct?

  3.  The manual uses the lingo `rep_cnt_suspect` and `rep_cnt_fail`  instead of `low_reps` and `high_reps`.  I made a mock-up PR (#58) using that but I guess we must be consistent and either change this test back to `{low,high}_reps` or change the original flat line test to use `rep_cnt_{fail,suspect}`.

The mock PR #58 implement this test.  However, just close it if that does not make sense and I can implement my suggestion in (1).

![flat_line](https://cloud.githubusercontent.com/assets/950575/10864693/4bf79a22-7fd5-11e5-8b94-ab2aef1a4c7e.png)

**Comment by ocefpaf** [comment]
I am starting to think that,

```python
@add_qartod_ident(16, 'Time Series Flat Line Test')
def ts_flat_line_check(arr, low_reps=3, high_reps=5, eps=None, prev_qc=None):
    return flat_line_check(arr, low_reps, high_reps, eps, prev_qc)
```

is the way to go here...
